#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import time

from scrapyd_manager import ScrapydManager
"""
 To run at the entrypoint for Docker container
 Features are
 - run for a period of time, then container will exit
 - clean up scrapyd.pid file as presence would prevent scrapyd start
 - Only need to deploy project on first start, not on restart, so check first

 arg 1: number of seconds scrapyd process to run for. Default 300.
"""

default_container_lifetime =  300

import scrape_utils
#try:

if len(sys.argv)  > 1:
    container_lifetime = float( sys.argv[1] )
else:
    container_lifetime = default_container_lifetime


scrapyd = ScrapydManager()
scrapyd.delete_pid_file()
scrapyd.start_service()
scrapyd.deploy_default()
time.sleep(container_lifetime)
#scrapyd.stop_service()