#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys
sys.path.append(os.path.join(os.getcwd(), "src"))
from scrapyd_manager import ScrapydManager

scrapyd = ScrapydManager()
scrapyd.stop_service()